# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('negotiable', models.BooleanField(default=True)),
                ('posted_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buysellapp.User'),
        ),
        migrations.AddField(
            model_name='interest',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buysellapp.User'),
        ),
        migrations.AddField(
            model_name='interest',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buysellapp.Item'),
        ),
    ]
