# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapp', '0002_auto_20170322_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
        migrations.AddField(
            model_name='interest',
            name='quoted_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
